##员工管理表 员工编号字段删除
ALTER TABLE TB_BASE_DELIVERY_EMPLOYEE DROP COLUMN USER_CODE;

##小区表 DELIVERY_FLAG字段删除
ALTER TABLE TB_BASE_COMMUNITY DROP COLUMN DELIVERY_FLAG;


ALTER  TABLE TB_SETTLE_DETAIL ADD  COLUMN  COMMUNITY_UNIT_ID INT COMMENT '小区单元ID';
ALTER  TABLE TB_SETTLE MODIFY COLUMN  TOTAL_TIME INT COMMENT '总时长';


#修改结算明细表
ALTER TABLE TB_SETTLE_DETAIL
ADD SETTLE_DT DATETIME NULL COMMENT '结算日期',
ADD BUILD_NAME VARCHAR(128) NULL COMMENT '楼栋名称',
ADD COMMUNITY_ID INT NULL COMMENT '小区编号',
ADD BUILDING_ID INT NULL COMMENT '楼栋编号',
ADD USER_ID INT NULL COMMENT '用户编号',
ADD TASK_ID INT NULL COMMENT '任务编号',
ADD DELIVERY_RESULT VARCHAR(32) NULL COMMENT '派送结果',
CHANGE COLUMN `NEIGHBORHOOD_NAME` `COMMUNITY_NAME`  VARCHAR(255) DEFAULT NULL COMMENT '小区名称',
CHANGE COLUMN `FLOOR_NUM` `BUILDING_NUM`  INT DEFAULT NULL COMMENT '楼栋数' ,
CHANGE COLUMN `UNIT_NUM` `COMMUNITY_UNIT_NUM`  INT DEFAULT NULL COMMENT '单元数';


#修改结算表
ALTER TABLE `TB_SETTLE`
DROP COLUMN `PRICE`,
DROP COLUMN `CAUSH_STATUS`,
CHANGE COLUMN `NEIGHBORHOODS_NUM` `COMMUNITY_NUM`  INT  DEFAULT NULL COMMENT '小区数',
CHANGE COLUMN `FLOOR_NUM` `BUILDING_NUM`  INT  DEFAULT NULL COMMENT '楼栋数' ,
CHANGE COLUMN `UNIT_NUM` `COMMUNITY_UNIT_NUM`  INT  DEFAULT NULL COMMENT '单元数';




#补贴信息表
CREATE TABLE TB_ALLOWANCE (
	ID  INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID' ,
	SETTLE_ID  INT NOT NULL COMMENT '结算编号' ,
	USER_ID INT NOT NULL COMMENT '用户编号',
	USER_NAME  VARCHAR(16) NOT NULL COMMENT '用户名称' ,
	TASK_ID  INT NOT NULL COMMENT '任务编号' ,
	ALLOWANCE_TYPE  VARCHAR(32) NOT NULL COMMENT '补贴类型' ,
	ALLOWANCE_AMOUNT  DOUBLE NOT NULL COMMENT '补贴金额',
	CREATE_DT DATETIME NULL COMMENT '创建时间',
	CREATE_USER VARCHAR(16) NULL COMMENT '创建人',
	PRIMARY KEY (ID)
);

