ALTER TABLE `TB_SETTLE`
ADD COLUMN `DELIVERY_CITY`  varchar(20) NULL COMMENT '派发城市信息' ;

ALTER TABLE `TB_DELIVERY_DATA_COMMUNITY`
ADD COLUMN `DELIVERY_CITY`  varchar(20) NULL COMMENT '派发城市信息' ;


ALTER TABLE `TB_DELIVERY_DATA_COMMUNITY_BUILDING`
ADD COLUMN `DELIVERY_CITY`  varchar(20) NULL COMMENT '派发城市信息' ;

ALTER TABLE `TB_DELIVERY_DATA_COMMUNITY_UNIT`
ADD COLUMN `DELIVERY_CITY`  varchar(20) NULL COMMENT '派发城市信息' ;


