

CREATE TABLE TB_SYS_USER (
  USER_ID int(11) NOT NULL AUTO_INCREMENT,
  USER_NAME varchar(20) NOT NULL,
  PASSWORD varchar(50) NOT NULL,
  USER_FLAG tinyint(4) DEFAULT '0' COMMENT '用户标志：0 正常状态；2 开店专员',
  STATUS_FLAG tinyint(4) NOT NULL DEFAULT '1',
  CREATE_USER  varchar(20) NULL,
  CREATE_DT  datetime NULL,
  MODIFY_USER varchar(20) DEFAULT NULL,
  MODIFY_TIME datetime DEFAULT NULL,
  PRIMARY KEY (USER_ID)
);

CREATE TABLE TB_SYS_ROLE (
  ROLE_ID int(11) NOT NULL AUTO_INCREMENT,
  ROLE_NAME varchar(20) NOT NULL,
  ROLE_DESC varchar(255) DEFAULT NULL,
  CREATE_USER  varchar(20) NULL,
  CREATE_DT  datetime NULL,
  MODIFY_USER varchar(20) DEFAULT NULL,
  MODIFY_TIME datetime DEFAULT NULL,
  PRIMARY KEY (ROLE_ID)
); 



CREATE TABLE TB_SYS_USER_ROLE (
  USER_ID int(11) NOT NULL,
  ROLE_ID int(11) NOT NULL,
  PRIMARY KEY (USER_ID,ROLE_ID),
  KEY USER_ID (USER_ID),
  KEY ROLE_ID (ROLE_ID),
  CREATE_USER  varchar(20) NULL,
  CREATE_DT  datetime NULL,
  MODIFY_USER  varchar(20) NULL,
  MODIFY_DT  datetime NULL,
  CONSTRAINT TB_SYS_USER_ROLE_ibfk_1 FOREIGN KEY (USER_ID) REFERENCES TB_SYS_USER (USER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT TB_SYS_USER_ROLE_ibfk_2 FOREIGN KEY (ROLE_ID) REFERENCES TB_SYS_ROLE (ROLE_ID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE TB_SYS_PLATFORM(
  ID int(11) NOT NULL AUTO_INCREMENT,
  NAME varchar(40) NOT NULL,
  URL  varchar(200) NOT NULL,
  SECRET_KEY varchar(64) NOT NULL,
  CREATE_USER  varchar(20) NULL,
  CREATE_DT  datetime NULL,
  MODIFY_USER  varchar(20) NULL,
  MODIFY_DT  datetime NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE ROLE_SECTION(
  ID int(11) NOT NULL AUTO_INCREMENT,
  ROLE_ID int(11) NOT NULL,
  SECTION_CITY varchar(64),
  SECTION_AREA varchar(64),
  SECTION_NAME varchar(64),
  SECTION_CODE varchar(64),
  CREATE_USER  varchar(20) NULL,
  CREATE_DT  datetime NULL,
  MODIFY_USER  varchar(20) NULL,
  MODIFY_DT  datetime NULL,
  PRIMARY KEY (ID)
);


CREATE TABLE TB_SYS_RESOURCES(
  ID int(11) NOT NULL AUTO_INCREMENT,
  NAME varchar(64) NOT NULL,
  DESCRIBER varchar(256) DEFAULT NULL,
  PARENT_ID int(11) NOT NULL,
  LEAF_FLAG tinyint(4) NOT NULL,
  LINK_URL varchar(256) DEFAULT NULL,
  ICON_CLS varchar(128) DEFAULT NULL,
  PLATFORM_ID  varchar(20) DEFAULT NULL,
  ORDERS int(4) NOT NULL DEFAULT '0',
  AUTHORIZE  varchar(32) NULL,
  CREATE_USER  varchar(20) NULL,
  CREATE_DT  datetime NULL,
  MODIFY_USER  varchar(20) NULL,
  MODIFY_DT  datetime NULL,
  UNIQUE(AUTHORIZE),
  PRIMARY KEY (ID)	
);

CREATE TABLE TB_SYS_ROLE_RESOURCES(
 ID int(16) NOT NULL AUTO_INCREMENT,
 ROLE_ID int(11) NOT NULL,
 RESOURCE_ID int(11) NOT NULL,
 CREATE_USER  varchar(20) NULL,
 CREATE_DT  datetime NULL,
 MODIFY_USER  varchar(20) NULL,
 MODIFY_DT  datetime NULL,
 PRIMARY KEY (ID)	
);

