DROP TABLE IF EXISTS TB_SYS_PLATFORM;
CREATE TABLE TB_SYS_PLATFORM(
  ID int(11) NOT NULL AUTO_INCREMENT,
  NAME varchar(40) NOT NULL,
  URL  varchar(200) NOT NULL,
  SECRET_KEY varchar(64) NOT NULL,
  CREATE_USER varchar(20) DEFAULT NULL,
  CREATE_DT datetime DEFAULT NULL,
  MODIFY_USER varchar(20) DEFAULT NULL,
  MODIFY_DT datetime DEFAULT NULL,
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS TB_SYS_RESOURCES;
CREATE TABLE TB_SYS_RESOURCES(
  ID int(11) NOT NULL AUTO_INCREMENT,
  NAME varchar(64) NOT NULL,
  DESCRIBER varchar(256) DEFAULT NULL,
  PARENT_ID int(11) NOT NULL,
  LEAF_FLAG tinyint(4) NOT NULL,
  LINK_URL varchar(256) DEFAULT NULL,
  ICON_CLS varchar(128) DEFAULT NULL,
  PLATFORM_ID  varchar(20) DEFAULT NULL,
  ORDERS int(4) NOT NULL DEFAULT '0',
  CREATE_USER  varchar(20) NULL,
  CREATE_DT  datetime NULL,
  MODIFY_USER  varchar(20) NULL,
  MODIFY_DT  datetime NULL,
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS ROLE_SECTION;
CREATE TABLE ROLE_SECTION(
  ID int(11) NOT NULL AUTO_INCREMENT,
  ROLE_ID int(11) NOT NULL,
  SECTION_CITY varchar(64),
  SECTION_AREA varchar(64),
  SECTION_NAME varchar(64),
  SECTION_CODE varchar(64),
  CREATE_USER  varchar(20) NULL,
  CREATE_DT  datetime NULL,
  MODIFY_USER  varchar(20) NULL,
  MODIFY_DT  datetime NULL,
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS TB_SYS_ROLE_RESOURCES;
CREATE TABLE TB_SYS_ROLE_RESOURCES(
 ID int(16) NOT NULL AUTO_INCREMENT,
 ROLE_ID int(11) NOT NULL,
 RESOURCE_ID int(11) NOT NULL,
 CREATE_USER  varchar(20) NULL,
 CREATE_DT  datetime NULL,
 MODIFY_USER  varchar(20) NULL,
 MODIFY_DT  datetime NULL,
 PRIMARY KEY (ID)	
)DEFAULT CHARSET=utf8;



ALTER TABLE TB_SYS_ROLE
ADD COLUMN CREATE_USER  varchar(20) NULL AFTER  ,
ADD COLUMN CREATE_DT  datetime NULL AFTER CREATE_USER;

ALTER TABLE TB_SYS_USER
ADD COLUMN CREATE_USER  varchar(20) NULL AFTER STATUS_FLAG,
ADD COLUMN CREATE_DT  datetime NULL AFTER CREATE_USER;

ALTER TABLE TB_SYS_USER_ROLE
ADD COLUMN CREATE_USER  varchar(20) NULL AFTER ROLE_ID,
ADD COLUMN CREATE_DT  datetime NULL AFTER CREATE_USER,
ADD COLUMN MODIFY_USER  varchar(20) NULL AFTER CREATE_DT,
ADD COLUMN MODIFY_DT  datetime NULL AFTER MODIFY_USER;

ALTER TABLE TB_SYS_USER ADD UNIQUE(USER_NAME);

ALTER TABLE TB_SYS_RESOURCES  ADD COLUMN  AUTHORIZE  varchar(32) NULL AFTER  ORDERS;
ALTER TABLE TB_SYS_RESOURCES  ADD UNIQUE(AUTHORIZE);



INSERT INTO `TB_SYS_PLATFORM`
(NAME,URL,SECRET_KEY,CREATE_USER,CREATE_DT,MODIFY_USER,MODIFY_DT)
VALUES ('权限管理平台', 'http://localhost:8082/hero', 't//d7sVmOW5qu6eSM4ktJ5E8ezSAYAMC', 'admin', now(), 'admin', now());

set @platformId = (SELECT ID FROM TB_SYS_PLATFORM WHERE NAME = '权限管理平台');

INSERT INTO `TB_SYS_RESOURCES`
(NAME, DESCRIBER, PARENT_ID, LEAF_FLAG, LINK_URL, ICON_CLS, PLATFORM_ID, ORDERS, AUTHORIZE, CREATE_USER, CREATE_DT, MODIFY_USER, MODIFY_DT)
VALUES ('权限管理', '权限管理', 0, 0, '', NULL, @platformId, 0, NULL, 'admin', now(), 'admin', now());


set @oneParentId = (SELECT ID FROM TB_SYS_RESOURCES WHERE PARENT_ID= '0');
INSERT INTO `TB_SYS_RESOURCES`
(NAME, DESCRIBER, PARENT_ID, LEAF_FLAG, LINK_URL, ICON_CLS, PLATFORM_ID, ORDERS, AUTHORIZE, CREATE_USER, CREATE_DT, MODIFY_USER, MODIFY_DT)
VALUES ('平台管理', '平台管理', @oneParentId, 0, '/platform', NULL, @platformId, 0, 'platform:search', 'admin', now(), 'admin', now());

INSERT INTO `TB_SYS_RESOURCES` 
(NAME, DESCRIBER, PARENT_ID, LEAF_FLAG, LINK_URL, ICON_CLS, PLATFORM_ID, ORDERS, AUTHORIZE, CREATE_USER, CREATE_DT, MODIFY_USER, MODIFY_DT)
VALUES ('平台用户管理', '平台用户管理', @oneParentId, 0, '/sysUser', NULL, @platformId, 1, 'sysUser:search', 'admin', now(), 'admin', now());

INSERT INTO `TB_SYS_RESOURCES` 
(NAME, DESCRIBER, PARENT_ID, LEAF_FLAG, LINK_URL, ICON_CLS, PLATFORM_ID, ORDERS, AUTHORIZE, CREATE_USER, CREATE_DT, MODIFY_USER, MODIFY_DT)
VALUES ('平台资源管理', '平台资源管理', @oneParentId, 0, '/resources', NULL, @platformId, 3, 'resources:search', 'admin', now(), 'admin', now());

INSERT INTO `TB_SYS_RESOURCES`
(NAME, DESCRIBER, PARENT_ID, LEAF_FLAG, LINK_URL, ICON_CLS, PLATFORM_ID, ORDERS, AUTHORIZE, CREATE_USER, CREATE_DT, MODIFY_USER, MODIFY_DT)
VALUES ('平台角色管理', '平台角色管理', @oneParentId, 0, '/sysRole', NULL, @platformId, 2, 'sysRole:search', 'admin', now(), 'admin', now());


set @platformParentId = (SELECT ID FROM TB_SYS_RESOURCES WHERE NAME = '平台管理');
INSERT INTO `TB_SYS_RESOURCES` 
(NAME, DESCRIBER, PARENT_ID, LEAF_FLAG, LINK_URL, ICON_CLS, PLATFORM_ID, ORDERS, AUTHORIZE, CREATE_USER, CREATE_DT, MODIFY_USER, MODIFY_DT)
VALUES ('新增平台', '新增平台', @platformParentId, 0, '/platform/add', NULL, @platformId, 0, 'platform:add', 'admin', now(), 'admin', now());

INSERT INTO `TB_SYS_RESOURCES` 
(NAME, DESCRIBER, PARENT_ID, LEAF_FLAG, LINK_URL, ICON_CLS, PLATFORM_ID, ORDERS, AUTHORIZE, CREATE_USER, CREATE_DT, MODIFY_USER, MODIFY_DT)
VALUES ('编辑平台', '编辑平台', @platformParentId, 0, '/platform/update', NULL, @platformId, 1, 'platform:update', 'admin', now(), 'admin', now());


set @userParentId = (SELECT ID FROM TB_SYS_RESOURCES WHERE NAME = '平台用户管理');
INSERT INTO `TB_SYS_RESOURCES`
(NAME, DESCRIBER, PARENT_ID, LEAF_FLAG, LINK_URL, ICON_CLS, PLATFORM_ID, ORDERS, AUTHORIZE, CREATE_USER, CREATE_DT, MODIFY_USER, MODIFY_DT)
VALUES ('编辑用户', '编辑用户', @userParentId, 0, '/sysUser/update', NULL, @platformId, 2, 'sysUser:update', 'admin', now(), 'admin', now());

INSERT INTO `TB_SYS_RESOURCES` 
(NAME, DESCRIBER, PARENT_ID, LEAF_FLAG, LINK_URL, ICON_CLS, PLATFORM_ID, ORDERS, AUTHORIZE, CREATE_USER, CREATE_DT, MODIFY_USER, MODIFY_DT)
VALUES ('新增用户', '新增用户', @userParentId, 0, '/sysUser/add', NULL, @platformId, 1, 'sysUser:add', 'admin', now(), 'admin', now());

INSERT INTO `TB_SYS_RESOURCES`
(NAME, DESCRIBER, PARENT_ID, LEAF_FLAG, LINK_URL, ICON_CLS, PLATFORM_ID, ORDERS, AUTHORIZE, CREATE_USER, CREATE_DT, MODIFY_USER, MODIFY_DT)
VALUES ('用户锁定', '用户锁定', @userParentId, 0, '/sysUser/setting', NULL, @platformId, 3, 'sysUser:lock', 'admin', now(), 'admin', now());

INSERT INTO `TB_SYS_RESOURCES`
(NAME, DESCRIBER, PARENT_ID, LEAF_FLAG, LINK_URL, ICON_CLS, PLATFORM_ID, ORDERS, AUTHORIZE, CREATE_USER, CREATE_DT, MODIFY_USER, MODIFY_DT)
VALUES ('用户解锁', '用户解锁', @userParentId, 0, '/sysUser/setting', NULL, @platformId, 4, 'sysUser:unlock', 'admin', now(), 'admin', now());

INSERT INTO `TB_SYS_RESOURCES` 
(NAME, DESCRIBER, PARENT_ID, LEAF_FLAG, LINK_URL, ICON_CLS, PLATFORM_ID, ORDERS, AUTHORIZE, CREATE_USER, CREATE_DT, MODIFY_USER, MODIFY_DT)
VALUES ('分配角色', '分配角色', @userParentId, 0, '/sysUser/assignRole', NULL, @platformId, 5, 'sysUser:assignRole', 'admin', now(), 'admin', now());


set @roleParentId = (SELECT ID FROM TB_SYS_RESOURCES WHERE NAME = '平台角色管理');
INSERT INTO `TB_SYS_RESOURCES`
(NAME, DESCRIBER, PARENT_ID, LEAF_FLAG, LINK_URL, ICON_CLS, PLATFORM_ID, ORDERS, AUTHORIZE, CREATE_USER, CREATE_DT, MODIFY_USER, MODIFY_DT)
VALUES ('新增角色', '新增角色', @roleParentId, 0, '/sysRole/add', NULL, @platformId, 1, 'sysRole:add', 'admin', now(), 'admin', now());

INSERT INTO `TB_SYS_RESOURCES`
(NAME, DESCRIBER, PARENT_ID, LEAF_FLAG, LINK_URL, ICON_CLS, PLATFORM_ID, ORDERS, AUTHORIZE, CREATE_USER, CREATE_DT, MODIFY_USER, MODIFY_DT)
VALUES ('编辑角色', '编辑角色', @roleParentId, 0, '/sysRole/update', NULL, @platformId, 2, 'sysRole:update', 'admin', now(), 'admin', now());

INSERT INTO `TB_SYS_RESOURCES`
(NAME, DESCRIBER, PARENT_ID, LEAF_FLAG, LINK_URL, ICON_CLS, PLATFORM_ID, ORDERS, AUTHORIZE, CREATE_USER, CREATE_DT, MODIFY_USER, MODIFY_DT)
VALUES ('分配资源', '分配资源', @roleParentId, 0, '/sysRole/searchResources', NULL, @platformId, 3, 'sysRole:assignResources', 'admin', now(), 'admin', now());

set @resourceParentId = (SELECT ID FROM TB_SYS_RESOURCES WHERE NAME = '平台资源管理');
INSERT INTO `TB_SYS_RESOURCES` 
(NAME, DESCRIBER, PARENT_ID, LEAF_FLAG, LINK_URL, ICON_CLS, PLATFORM_ID, ORDERS, AUTHORIZE, CREATE_USER, CREATE_DT, MODIFY_USER, MODIFY_DT)
VALUES ('新增资源', '新增资源', @resourceParentId, 0, '/resources/add', NULL, @platformId, 1, 'resources:add', 'admin', now(), 'admin', now());

INSERT INTO `TB_SYS_RESOURCES`
(NAME, DESCRIBER, PARENT_ID, LEAF_FLAG, LINK_URL, ICON_CLS, PLATFORM_ID, ORDERS, AUTHORIZE, CREATE_USER, CREATE_DT, MODIFY_USER, MODIFY_DT)
VALUES ('编辑资源', '编辑资源', @resourceParentId, 0, '/resources/update', NULL, @platformId, 2, 'resources:update', 'admin', now(), 'admin', now());

INSERT INTO `TB_SYS_RESOURCES` 
(NAME, DESCRIBER, PARENT_ID, LEAF_FLAG, LINK_URL, ICON_CLS, PLATFORM_ID, ORDERS, AUTHORIZE, CREATE_USER, CREATE_DT, MODIFY_USER, MODIFY_DT)
VALUES ('删除资源', '删除资源', @resourceParentId, 0, '/resources/deleteResources', NULL, @platformId, 3, 'resources:deleteResources', 'admin', now(), 'admin', now());


INSERT INTO TB_SYS_ROLE_RESOURCES (ROLE_ID,RESOURCE_ID,CREATE_USER,CREATE_DT,MODIFY_USER,MODIFY_DT) select '1', ID,'admin',NOW(),'admin',NOW() FROM TB_SYS_RESOURCES;

