CREATE TABLE TB_SYS_PLATFORM(
  ID int(11) NOT NULL,
  NAME varchar(40) NOT NULL,
  URL  varchar(200) NOT NULL,
  SECRET_KEY varchar(64) NOT NULL,
  CREATE_USER varchar(20) DEFAULT NULL,
  CREATE_DT datetime DEFAULT NULL,
  MODIFY_USER varchar(20) DEFAULT NULL,
  MODIFY_DT datetime DEFAULT NULL,
  PRIMARY KEY (ID)
);

ALTER TABLE TB_SYS_ROLE
ADD COLUMN CREATE_USER  varchar(20) NULL AFTER ROLE_DESC,
ADD COLUMN CREATE_DT  datetime NULL AFTER CREATE_USER;

ALTER TABLE TB_SYS_USER
ADD COLUMN CREATE_USER  varchar(20) NULL AFTER STATUS_FLAG,
ADD COLUMN CREATE_DT  datetime NULL AFTER CREATE_USER;


ALTER TABLE TB_SYS_USER_ROLE
ADD COLUMN CREATE_USER  varchar(20) NULL AFTER ROLE_ID,
ADD COLUMN CREATE_DT  datetime NULL AFTER CREATE_USER,
ADD COLUMN MODIFY_USER  varchar(20) NULL AFTER CREATE_DT,
ADD COLUMN MODIFY_DT  datetime NULL AFTER MODIFY_USER;


CREATE TABLE TB_SYS_RESOURCES(
  ID int(11) NOT NULL AUTO_INCREMENT,
  NAME varchar(64) NOT NULL,
  DESCRIBER varchar(256) DEFAULT NULL,
  PARENT_ID int(11) NOT NULL,
  LEAF_FLAG tinyint(4) NOT NULL,
  LINK_URL varchar(256) DEFAULT NULL,
  ICON_CLS varchar(128) DEFAULT NULL,
  PLATFORM_ID  varchar(20) DEFAULT NULL,
  ORDERS int(4) NOT NULL DEFAULT '0',
  CREATE_USER  varchar(20) NULL,
  CREATE_DT  datetime NULL,
  MODIFY_USER  varchar(20) NULL,
  MODIFY_DT  datetime NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE ROLE_SECTION(
  ID int(11) NOT NULL AUTO_INCREMENT,
  ROLE_ID int(11) NOT NULL,
  SECTION_CITY varchar(64),
  SECTION_AREA varchar(64),
  SECTION_NAME varchar(64),
  SECTION_CODE varchar(64),
  CREATE_USER  varchar(20) NULL,
  CREATE_DT  datetime NULL,
  MODIFY_USER  varchar(20) NULL,
  MODIFY_DT  datetime NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE TB_SYS_ROLE_RESOURCES(
 ID int(16) NOT NULL AUTO_INCREMENT,
 ROLE_ID int(11) NOT NULL,
 RESOURCE_ID int(11) NOT NULL,
 CREATE_USER  varchar(20) NULL,
 CREATE_DT  datetime NULL,
 MODIFY_USER  varchar(20) NULL,
 MODIFY_DT  datetime NULL,
 PRIMARY KEY (ID)	
);
